// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

var helloSayHelloStreamDesc = &grpc.StreamDesc{
	StreamName: "SayHello",
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/hello.Hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloService is the service API for Hello service.
// Fields should be assigned to their respective handler implementations only before
// RegisterHelloService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type HelloService struct {
	SayHello func(context.Context, *HelloRequest) (*HelloReply, error)
}

func (s *HelloService) sayHello(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/hello.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterHelloService registers a service implementation with a gRPC server.
func RegisterHelloService(s grpc.ServiceRegistrar, srv *HelloService) {
	srvCopy := *srv
	if srvCopy.SayHello == nil {
		srvCopy.SayHello = func(context.Context, *HelloRequest) (*HelloReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "hello.Hello",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "SayHello",
				Handler:    srvCopy.sayHello,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "grpc/hello/hello.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewHelloService creates a new HelloService containing the
// implemented methods of the Hello service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewHelloService(s interface{}) *HelloService {
	ns := &HelloService{}
	if h, ok := s.(interface {
		SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	}); ok {
		ns.SayHello = h.SayHello
	}
	return ns
}

// UnstableHelloService is the service API for Hello service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableHelloService interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}
